variable "env"{}
variable "component"{}
variable "instance_type"{}
variable "subnet_ids"{}
variable "port"{}
variable "allow_subnets"{}
variable "priority"{}
variable "vpc_id"{}
variable "alb_dns_name"{}
variable "listener_arn"{}